version: "3.9"
services:
  scpipe_mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
  
  scpipe_collector:
    build: 
      context: .
      dockerfile: Dockerfile-sc_crawler
    depends_on:
      - "scpipe_mongo"
      - "scpipe_mysql"
  
  scpipe_mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldb/database.sql:/docker-entrypoint-initdb.d/database.sql
    env_file:
        - ./mysqldb/env_file.env

  scpipe_transformer:
    build: 
      context: .
      dockerfile: Dockerfile-sc_transformer
    depends_on:
      - "scpipe_mysql"
      - "scpipe_collector"
