FROM python:3.8

# Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
    apt-get -y update && apt-get install -y google-chrome-stable && \
    apt-get install -yqq unzip && \
    apt-get clean

WORKDIR /code
COPY ./sc_crawler /code
COPY ./collector /code/collector

# Setup chromedriver
RUN latest=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/"$latest"/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/ && rm /tmp/chromedriver.zip

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

ENTRYPOINT [ "python", "extract.py", '--nu', '1000', '--nr', '1000']